In [58]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

In [59]:
df = pd.read_csv("/Users/mohddanish/Desktop/Machine_Learning/MachineLearning/Feature_Engineering/FeatureTransformation/customer.csv")

In [60]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [61]:
# check how many unique values in education column
df["education"].nunique()

3

Applying ordinal encoding on review and education columns and label encoding on purchased column

In [62]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])
le = LabelEncoder()

In [63]:
# applying ordinal encoding on review and education columns
# encode_review = oe.fit_transform(df[["review"]])
# encode_education = oe.fit_transform(df[["education"]])
# # add new columns to the dataframe
# df["review_ordinal"] = encode_review
# df["education_ordinal"] = encode_education


oe_review = OrdinalEncoder(categories=[['Poor', 'Average', 'Good']])
oe_edu = OrdinalEncoder(categories=[['School', 'UG', 'PG']])

df["review_ordinal"] = oe_review.fit_transform(df[["review"]])
df["education_ordinal"] = oe_edu.fit_transform(df[["education"]])

In [64]:
df.head()

   age  gender   review education purchased  review_ordinal  education_ordinal
0   30  Female  Average    School        No             1.0                0.0
1   68  Female     Poor        UG        No             0.0                1.0
2   70  Female     Good        PG        No             2.0                2.0
3   72  Female     Good        PG        No             2.0                2.0
4   16  Female  Average        UG        No             1.0                1.0

In [65]:
purchase_label = le.fit_transform(df["purchased"])
df["purchased_label"] = purchase_label
df.head()

,age,gender,review,education,purchased,review_ordinal,education_ordinal,purchased_label
0,30,Female,Average,School,No,1.0,0.0,0
1,68,Female,Poor,UG,No,0.0,1.0,0
2,70,Female,Good,PG,No,2.0,2.0,0
3,72,Female,Good,PG,No,2.0,2.0,0
4,16,Female,Average,UG,No,1.0,1.0,0

In [66]:
print(oe_review.categories_)
print(oe_edu.categories_)

[array(['Poor', 'Average', 'Good'], dtype=object)]
[array(['School', 'UG', 'PG'], dtype=object)]