In [124]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, OneHotEncoder

In [125]:
df = pd.read_csv('/Users/mohddanish/Desktop/Machine_Learning/MachineLearning/Feature_Engineering/FeatureTransformation/cars.csv')

In [126]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [127]:
train_X, test_X, train_y, test_y = train_test_split(df.iloc[:, 0:4], df.iloc[:,-1], test_size=0.2, random_state=42)

In [128]:
train_X.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [129]:
# train_X["fuel"].unique()
train_X["owner"].unique()

<ArrowStringArray>
[         'First Owner',         'Second Owner', 'Fourth & Above Owner',
          'Third Owner',       'Test Drive Car']
Length: 5, dtype: str

In [130]:
ohe = OneHotEncoder()
ohe.fit(train_X[["fuel", "owner"]])
X_train_new = ohe.transform(train_X[["fuel", "owner"]]).toarray()
test_X_new = ohe.transform(test_X[["fuel", "owner"]]).toarray()

In [ ]:
data = train_X.iloc[:, 0:2]

In [145]:
# append with X_train_new
X_train_new = np.hstack((data, X_train_new))
X_train_new

array([['Tata', 2560, 'Tata', ..., 0.0, 0.0, 0.0],
       ['Honda', 80000, 'Honda', ..., 1.0, 0.0, 0.0],
       ['Hyundai', 150000, 'Hyundai', ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 35000, 'Hyundai', ..., 0.0, 0.0, 0.0],
       ['Maruti', 27000, 'Maruti', ..., 0.0, 0.0, 0.0],
       ['Maruti', 70000, 'Maruti', ..., 1.0, 0.0, 0.0]],
      shape=(6502, 15), dtype=object)

In [146]:
df['brand'].unique()

<ArrowStringArray>
[       'Maruti',         'Skoda',         'Honda',       'Hyundai',
        'Toyota',          'Ford',       'Renault',      'Mahindra',
          'Tata',     'Chevrolet',          'Fiat',        'Datsun',
          'Jeep', 'Mercedes-Benz',    'Mitsubishi',          'Audi',
    'Volkswagen',           'BMW',        'Nissan',         'Lexus',
        'Jaguar',          'Land',            'MG',         'Volvo',
        'Daewoo',           'Kia',         'Force',    'Ambassador',
         'Ashok',         'Isuzu',          'Opel',       'Peugeot']
Length: 32, dtype: str

In [150]:
counts = df['brand'].value_counts()

In [160]:
threshold = 100

# get brands with count < threshold
rare_brands = counts[counts <= threshold].index
most_frequent_brands = counts[counts >= threshold].index

rare_brands

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Kia',
       'Ambassador', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='str', name='brand')

In [155]:
most_frequent_brands

Index(['Maruti', 'Hyundai', 'Mahindra', 'Tata', 'Toyota', 'Honda', 'Ford',
       'Chevrolet', 'Renault', 'Volkswagen', 'BMW', 'Skoda'],
      dtype='str', name='brand')